method: grid
metric:
  name: auc_micro
  goal: maximize
parameters:
  learning_rate:
    value: 1e-4

  batch_size:
    value: 16

  epochs:
    value: 15

  weight_decay:
    value: 1e-5

  dropout:
    value: 0.4

  max_len:
    value: 512

  loss_func:
    value: BCE

  #bvanaken/CORe-clinical-outcome-biobert-v1, dmis-lab/biobert-v1.1
  backbone:
    value: nlpie/tiny-clinicalbert

  #la
  attn:
    value: la

  #hetero
  graph:
    value: hetero

  cluster:
    value: group

  fusion:
    value:

  cls:
    value: fc

  temp:
    value: 0.07

  lamb:
    value: 0.4