name: EMSProject
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - torchaudio
  - pytorch
  - torchvision
  - transformers
  - nltk
  - ipykernel
  - opencv
  - protobuf
  - grpcio
  - pyqt
  - sqlite
  - typing_extensions
  - zeromq
  - xz
  - zlib
  - libffi
  - libgcc-ng
  - libstdcxx-ng
  - ca-certificates
  - pip:
    - absl-py
    - beautifulsoup4
    - flask
    - flask-socketio
    - google-api-core
    - google-cloud-speech
    - huggingface-hub
    - jinja2
    - jiwer
    - matplotlib-inline
    - mediapipe
    - opencv-python
    - protobuf
    - pygame
    - pytest
    - sounddevice
    - torch-geometric
    - torch-scatter
    - torch-sparse
    - tqdm
    - websocket-client
    - werkzeug
